### ISSUE TITLE
missing_msg for check_output_expr() gives too much away

### ISSUE THREAD

**Issue by richierocks** [datacamp/testwhat#102]
One of the most common pieces of feedback I'm seeing from beta testers is that the default message for `check_output_expr()` gives too much information away, since it tells the student the exact code that they should have written.

This means that I always have to override the `missing_msg` argument.

For example, one exercise asked for this output-creating expression to be written by the user

```r
str_extract_all(contact, phone_pattern)
```

The default message is

```
Did your code produce the same output as str_extract_all(contact, phone_pattern)? 
```

I'm not quite sure what the optimal default response is. Maybe something like:

```
Expecting output from a call to `str_extract_all()`, but did not find the correct values.
```

I think it's worth thinking if we can come up with something better.

**Comment by filipsch** [comment]
It's very hard to do this automatically. As the wiki suggests, currently, you'll often want to manually set the feedback in `test_output_contains()` or `check_output_expr()`..

**Comment by machow** [comment]
I agree with Filip, the issue seems to be that the right feedback message may depend on information that can't be pulled from the code of an exercise alone.

**Comment by richierocks** [comment]
OK, if it can't be done, it can't be done.
