### ISSUE TITLE
Error with lapply in test_output_contains()

### ISSUE THREAD

**Issue by hermandr** [datacamp/testwhat#111]
Hi,
I tried to knit chapter1.Rmd of courses-intro-to-r.
I encountered error when processing this line:
test_output_contains("18", incorrect_msg = "Make sure to add `6 + 12` on a new line. Do not start the line with a `#`, otherwise your R code is not executed!")
Error:
Quitting from lines 53-55 (chapter1.Rmd) 
Error in lapply(X = X, FUN = FUN, ...) : attempt to apply non-function
Calls: <Anonymous> ... convert_output_list -> which -> %in% -> sapply -> lapply

Execution halted 

Any assistance would be appreciated.

Herman

**Comment by machow** [comment]
Hey Herman, DataCamp courses use some extra special syntax in the .Rmd files. See https://www.datacamp.com/teach/documentation for how to create an open DataCamp course. If you want to embed DataCamp into a web page, see https://github.com/datacamp/datacamp-light.
