### ISSUE TITLE
check_arg -> check_equal seems erratic

### ISSUE THREAD

**Issue by machow** [datacamp/testwhat#114]
From pairing w/ @nicksolomon , exercises 4 and 5 of chapter 2 give unexpected feedback when you try to fail the first argument of the first predict call.

https://github.com//datacamp/courses-supervised-learning-in-r-classification/tree/scts

Need to try and replicate / trim down to a smaller example

**Comment by filipsch** [comment]
@nicksolomon can you chime in here and provide me with a minimally reproducible example if this is still an issue? It's hard to start digging into the issue with this limited amount of information. If there is no more issue for you, I will close it and will see it re-appear again if somebody stumbles across it in the future.

**Comment by filipsch** [comment]
No reply, I consider this solved. You can open a new issue if something pops up in the future.
