### ISSUE TITLE
Support SCTs for Rcpp courses

### ISSUE THREAD

**Issue by rv2e** [datacamp/testwhat#118]
@richierocks commented on [Mon Jun 26 2017](https://github.com/datacamp/pm-learn/issues/140)

### Summary of Issue

The SCT infrastructure needs a little work to support Rcpp courses.

After a discussion with @machow, the minimal viable product needs 3 features, one of which seems to work already.

The thing that works is that `test_error()` correctly gives feedback if the C++ doesn't compile.

The second feature that is needed is to allow existing `testwhat` functionality to work with the R code contained in the `/*** R` block. See, e.g., Ch1 Ex3 of the [Test Rcpp course](https://www.datacamp.com/teach/edit/repositories/1154/branches/master).

The third feature is to have a `check_code()`/`test_student_typed()` functionality for the C++ block of the student's code.

---

@ramnathv commented on [Tue Jun 27 2017](https://github.com/datacamp/pm-learn/issues/140#issuecomment-311266373)

@machow any thoughts on how these can be achieved by writing an extension to `testwhat`?

The second feature should work out of the box imo once the C++ file is run through `sourceCpp`, since that should make all the R objects available in the environment and hence standard `testwhat` syntax should work.

The third feature is a lot trickier, since it means writing a `testcpp` module. It would be useful to get some references on how this is usually done, before we figure out what we should do. @richierocks can you collect some references on this, maybe after talking to Romain?

---

@machow commented on [Tue Jun 27 2017](https://github.com/datacamp/pm-learn/issues/140#issuecomment-311365550)

@ramnathv for testwhat to work with the R code in the c++ file, we will need to have testwhat pull out the contents of all the `***R` blocks (seems pretty grep-able). Once that's done, the R specific code can be treated like it's just another R script by the SCTs.

The third feature (`test_student_typed` / `check_code`) already works.

---

@ramnathv commented on [Tue Jun 27 2017](https://github.com/datacamp/pm-learn/issues/140#issuecomment-311366185)

@machow The third feature works with C++ blocks? How?

---

@machow commented on [Tue Jun 27 2017](https://github.com/datacamp/pm-learn/issues/140#issuecomment-311375534)

> The third feature is to have a check_code()/test_student_typed() functionality for the C++ block of the student's code.

In adapting the r-backend for rcpp, @filipsch set it so that `testwhat` never stops due to a syntax error, so all the SCTs that only use raw code text still work. Further, `testwhat` has no parsed code data, and no objects in the student and solution environments.

The categories of tests that we could support are

* raw text based (e.g. `test_student_typed`) **implemented**.
* objects in environment (e.g. `test_object`, ~~not sure how this works with Rcpp, would need changes to r-backend.~~ edit: this is simple to implement.)
* based AST or parsing code (e.g. `check_function`)

---

@filipsch commented on [Wed Jun 28 2017](https://github.com/datacamp/pm-learn/issues/140#issuecomment-311586243)

@machow cc @richierocks I looked into enabling RBackend to also run the CPP and R code in the comments in the solution environment, so that you can use stuff like `test_object()`. 

`sourceCpp()` allows you to specify the `env` argument, but that only applies to the Cpp-defined R functions and modules (the cpp part of the script). The variables that result from running the R code in comments will not be in that environment. This complicates things a bit.

If we want to have a full-blown solution environment with the Rcpp-defined functions and modules, and in addition the R objects created in the comments, we would have to:
- patch `sourceCpp()`, or 
- separate out the Cpp code from the R code up front and run it separately (with `sourceCpp()` and `source()`.

In any case, it's more work and more sources for bugs.

I suggest that for now, we only run the code in the global envrionment. If we find a solid way of separating out R code from RCpp code later on (for testing purposes), we can still slot it in in RBackend as well. 

Until then, if you still want to use stuff like `test_object()`, you can manually populate the solution environment:

```R
ex() %>% override_solution(x = 6765) %>% check_object('fib_result') %>% check_equal()
```

---

@machow commented on [Wed Jun 28 2017](https://github.com/datacamp/pm-learn/issues/140#issuecomment-311589205)

Note that the problematic code is [here](https://github.com/RcppCore/Rcpp/blob/d6ec27fc613b209db1bbab599b251becd4303434/R/Attributes.R#L196-L200). The problem is similar to the one we had with `RBayesX`. In this case, AFAIK they should add a `local = parent.frame()` arg to source.

edit: or pass the env argument to that `source`.

---

@filipsch commented on [Wed Jun 28 2017](https://github.com/datacamp/pm-learn/issues/140#issuecomment-311599385)

I feel a PR to Rcpp coming

![spagett](https://user-images.githubusercontent.com/5768479/27628819-7e49626e-5bf0-11e7-910b-82a5beda2e07.gif)

**Comment by machow** [comment]
I opened an issue specific to parsing the R code from an Rcpp file. Since the changes that need to made to the Rcpp library fall outside the scope of testwhat, I'm closing this one, but let me know if you need help on where to modify Rcpp.

**Comment by filipsch** [comment]
This has been addressed now. There's a [PR open on the RCpp course](https://github.com/datacamp/courses-integrating-cpp-and-r-with-rcpp/pull/15) that shows off the functionality that's there.
