### ISSUE TITLE
Parse R code from Rcpp files

### ISSUE THREAD

**Issue by machow** [datacamp/testwhat#119]
split from issue #118. When a student makes a submission for an Rcpp course, their code is run through the R parser. Since it is not valid R code, it fails gracefully, making tests like `test_function` impossible. 

cc @richierocks, I'll walk through this issue tomorrow to demonstrate how testwhat works.

## Relevant lines of code

* [where code is parsed in test_exercise](https://github.com/datacamp/testwhat/blob/4b475aa1aaae05e295f816075efcdbdfecbfd115/R/test-exercise.R#L47)
* [build_pd, which does the parsing](https://github.com/datacamp/testwhat/blob/7b56e2af65a37e126ab0afa4d8fed2e112d2758a/R/utils-pd.R#L2)

## How to implement

Since the testwhat `state` object holds the student and solution code, we could create a new function used in the SCT block which pulls out the R code from an Rcpp file and puts it on the state. E.g. in an SCT block...

```
parsed_state <- ex() %>% parse_rcpp()

parsed_state %>% check_function(...)
```

**Sketch of parse_rcpp**

```
parse_rcpp <- function(state) {
  # make child state, to avoid mutating parent
  child <- ChildState$new(state)
  child$set(student_pd = PARSING_LOGIC,
            solution_pd = PARSING_LOGIC)

  child
}
```

**Comment by filipsch** [comment]
Iceboxing this until this requirement pops up again.

**Comment by machow** [comment]
I think that Rcpp SCTs @richierocks built were merged into testwhat. https://github.com/datacamp/testwhat/commit/383e71cfb5779443a399815f5dcef44ddcdbc2c9

**Comment by filipsch** [comment]
Closing then!
