### ISSUE TITLE
Allow for multiple valid solutions with differing outputs

### ISSUE THREAD

**Issue by sritchie73** [datacamp/testwhat#123]
I'm looking for a way to test for multiple valid solutions, where each solution gives a different (but equivalent) output. I cannot see a way to do this right now.

Here's an example:

In my exercise I ask students to perform an inner join on the following two data.frames:

```{r}
> df1 <- data.frame(id=c("a", "b"), val=1:2)
> df2 <- data.frame(id=c("a", "b"), col=c("red", "blue")
```
The following are both valid solutions:

```{r}
> merge(df1, df2, by="id")
  id val  col
1  a   1  red
2  b   2 blue
```

```{r}
> merge(df2, df1, by="id")
  id  col val
1  a  red   1
2  b blue   2
```
The output objects are equivalent in the sense that they contain the same information, however the ordering of columns depends on the ordering of input arguments to the merge function.

It would be nice to have a function like `test_is_one_of(...)`  that takes an arbitrary number of `test_*` functions of the same type that checks to see if one of the `test_*` functions returns whatever object triggers the success state.

**Comment by filipsch** [comment]
@sritchie73 thanks for the detailed question. You can find more information about 'allowing for different solutins' in [this wiki article](https://github.com/datacamp/testwhat/wiki/test_function#example-6-allowing-for-different-solutions). Specifically for you, the SCT would look as follows, if the solution you listed is the first one:

```R
test_or({
  fun <- ex() %>% check_function('merge')
  fun %>% check_arg('x') %>% check_equal()
  fun %>% check_arg('y') %>% check_equal()
  fun %>% check_arg('by') %>% check_equal()
}, {
  fun <- ex() %>% override_solution('merge(df1, df2, by="id")') %>% check_function('plot')
  fun %>% check_arg('x') %>% check_equal()
  fun %>% check_arg('y') %>% check_equal()
  fun %>% check_arg('by') %>% check_equal()
})
```

I didn't test myself, so let me know if it does not work out.

You could also test the output that these functions generate:

```R
test_or(test_output_contains('merge(df2, df1, by="id")', test_output_contains('merge(df1, df2, by="id")'))
```

If you use this, make sure to use manually set `incorrect_msg` arguments, as the automatically generated ones are very revealing.

Hope this helped!

**Comment by sritchie73** [comment]
Thanks @filipsch , that's exactly what I was looking for!

**Comment by filipsch** [comment]
@sritchie73 Cool! if this solves your question, feel free to close the issue. Cheers.
