### ISSUE TITLE
check_fun_def() fails with nested function definitions

### ISSUE THREAD

**Issue by nicksolomon** [datacamp/testwhat#124]
When defining a function inside another function using `ex() %>% check_fun_def("outer_fun") %>% check_body()` fails with an error about not being able to find the function `outer_fun` defined in the solution code.

For an example see chapter 3 exercise 17 of https://www.datacamp.com/teach/repositories/1389/branches/sct-issue

**Comment by yashasroy** [comment]
@richierocks In lieu of actually deploying an update on `testwhat` to fix this issue, ideas / suggestions on feasible workarounds would be appreciated. I suggest we set aside 30 minutes to discuss this in person.

**Comment by machow** [comment]
Sorry--this popped up when I was away on vacation. Were you able to find a work around? How urgent is this issue?
