### ISSUE TITLE
Move core functionality into a testwhat.base pkg

### ISSUE THREAD

**Issue by richierocks** [datacamp/testwhat#128]
At the moment, testwhat.ext depends upon testwhat and R-backend.

The only things it needs from testwhat are
```
tw
RootState
ChildState
DC_Reporter
build_pd()
get_num_hits()
```

These (and maybe the other classes) should be moved to a new package, `testwhat.base`, so `testwhat.ext` can depend upon that.

`testwhat` can reexport the existing functionality from `testwhat.base` so that existing courses won't be able to tell the difference.

**Comment by filipsch** [comment]
AFAIK, `testwhat.ext` does not depend on `RBackend`, and neither does `testwhat`. It's the other way around, `testwhat` depends on `RBackend`. 

`testwhat.ext` _does_ depend on `testwhat`.

In any case, the solution, IMO, is to just install `testwhat.ext` without installing its dependencies in the course image. When the course image is spinned up and the shared images are volume-mounted into the course container, `testwhat.ext` will find `testwhat` in the shared path, and it will simply work.

See https://github.com/datacamp/protowhat/issues/18 for more context.

I'll do a PR for the developing R packages course to illustrate this practice, and verify that it works. If it works, I will close icebox this issue, as I don't think it's the most important thing to do right now and it's not really solving any problems.

**Comment by filipsch** [comment]
@richierocks after giving it some more thought, I follow your thinking. I'll create a testwhat.base package with core functionality that is also used by `testwhat.ext`. It will also include some other stuff, such as `is_gte`, `is_equal`, `check_that`, etc, so testwhat.ext no longer has to depend on `testwhat`.

**Comment by filipsch** [comment]
PRs have been opened on both testwhat and testwhat.ext

**Comment by filipsch** [comment]
@richierocks as discussed yesterday, I decided to group together everything in `testwhat` in the end, exposing the functions that `testwhat.ext` currently needs. `RBackend` is no longer a dependency of `testwhat`, so installing `testwhat.ext` should also be easier (all open-source packages).

As more and more functions are added to `testwhat.ext`, I hope to start to see a pattern of what functionality from `testwhat` is typically needed from it and would make sense for a split. Same for `testwhat` itself; as it goes through another round of refactor, I hope to see a pattern emerge of groups of functions that serve a particular need, and would call for a package split. We'll see!

**Comment by filipsch** [comment]
By the way, see https://github.com/datacamp/testwhat.ext/pull/7
