### ISSUE TITLE
Get diff-viewer up and running on new cluster

### ISSUE THREAD

**Issue by filipsch** [datacamp/testwhat#130]

**Comment by machow** [comment]
cc @ramnathv who is using it as an API for content analyses, and may need to update URLs once the service is moved.

**Comment by ramnathv** [comment]
@filipsch As @machow indicated,  I am using the `diff-viewer` as an API to grab incorrect attempts data for exercises that require maintenance. I would appreciate if you can give me a heads up when the url changes!

**Comment by filipsch** [comment]
@ramnathv which URL are you using right now?

**Comment by ramnathv** [comment]
@filipsch I am using http://diff-viewer.herokuapp.com/ex/

**Comment by filipsch** [comment]
Issue moved to [datacamp/diff-viewer #6](https://github.com/datacamp/diff-viewer/issues/6) via [**ZenHub**](https://www.zenhub.com/)
