### ISSUE TITLE
Revisit unpipe functionality

### ISSUE THREAD

**Issue by filipsch** [datacamp/testwhat#140]
It's messy, and I don't know what's going on. https://github.com/rstudio-education/grader/blob/master/R/unpipe.R can serve as inspiration.

**Comment by filipsch** [comment]
It's still working. grader can only unpipe once. Will only revisit when it poses issues.

**Comment by ramnathv** [comment]
@filipsch In `sctbuilder`, I have an implementation that unpipes recursively. There is a small bug in the implementation of `unpipe` in `grader`, and I have a fix that I will commit soon.

**Comment by ramnathv** [comment]
@filipsch I would be happy to :) Can you point me to the **messy code** you were referring to in the first place ;)

**Comment by filipsch** [comment]
https://github.com/datacamp/testwhat/blob/master/R/utils-function.R#L149-L183
