### ISSUE TITLE
Remove dependency on RBackend

### ISSUE THREAD

**Issue by filipsch** [datacamp/testwhat#146]
Close to all unit tests in testwhat just simulate RBackend submissions. It should be less integration test, more unit test, and more decoupled. That way, also people outside of DataCamp can contribute to the package and it can be used by other platforms as well, potentially.

**Comment by filipsch** [comment]
Dependency is removed now cc @machow.
Tests run an order of magnitude faster.

**Comment by machow** [comment]
Ah, nice--this is huge!

**Comment by filipsch** [comment]
Check out the README of testwhat, you can also do the following now:

```R
library(testwhat)
setup_state(stu_code = "x <- 4", sol_code = "x <- 5")
ex() %>% check_object() %>% check_equal()
```
