### ISSUE TITLE
Update check_header() feedback messages

### ISSUE THREAD

**Issue by nicksolomon** [datacamp/testwhat#179]
Currently the feedback message is something like "Check the first `h2` header." Is it possible to replace `h2` with something like "second level"? I think students might not be familiar with what `h2` means.

**Comment by filipsch** [comment]
@nicksolomon sure thing. That would mean that you can end up with messages like these:

- Check the first second level header
- Check the second first level header
- ...

Maybe that is confusing? Rather, I suggest something like:

- Check the first level 2 header
- Check the second level 1 header

WDYT?

FYI: Too bad there is no highlighting for this stuff yet, but it's not worth the time investment at the moment. If we end up shipping tons of MarkdownExercise in courses, this might be something to explore.
