### ISSUE TITLE
test_ggplot() fails with geom_jitter() width arg

### ISSUE THREAD

**Issue by richierocks** [datacamp/testwhat#182]
I created a ggplot that used `geom_jitter()` with the `width` argument. I tested it with `test_ggplot()`. I got the error

```
In your first ggplot command, have you correctly added a geom_jitter() layer with the position set correctly? Have another look at the instructions. 
```

To reproduce, see ch1ex1 of 

https://www.datacamp.com/teach/repositories/986/branches/ggplot-jitter-issue

This affects the in-progress rewrite of ggplot2 Part 1.

**Comment by filipsch** [comment]
@richierocks I want to phase out `test_ggplot()` or it's younger brother `ex() %>% check_ggplot()`, as it's a 'one stop shop magic function that checks everything but you don't really know what'. Issues will keep popping up, requiring me to keep sinking time into this.

Rather, I suggest you just use  `check_function`. There's an example [here](http://datacamp.github.io/testwhat/articles/glossary.html#check-ggplot):

```
ex() %>% {
  check_function(., "ggplot") %>% check_arg("data") %>% check_equal()
  check_function(., "aes") %>% {
    check_arg(., "x") %>% check_equal(eval = FALSE) 
    check_arg(., "y") %>% check_equal(eval = FALSE)
  }
  check_function(., "geom_point")
}
```

Although maybe not as ideal, would this solve your problem?

**Comment by richierocks** [comment]
`test_ggplot()` is deprecated, so closing.
