### ISSUE TITLE
Minor documentation feedback

### ISSUE THREAD

**Issue by Hadrien-lcrx** [datacamp/testwhat#192]
## DataFrame or omitted double quotes?
* `print(mtcars)` or `print("mtcars")`
* impact of `check_output_expr()`

[Source](https://datacamp.github.io/testwhat/articles/glossary.html#check-output)

## Vague definition

> The functions in `testwhat` related to testing functions allow you to test whether students correctly called particular functions, with **the correct arguments and whether these arguments are correct.**

* The functions in `testwhat` related to testing functions allow you to test whether students correctly called particular functions, with **the expected arguments and whether the values passed to these arguments are correct.**

[Source](https://datacamp.github.io/testwhat/articles/checking-function-calls.html)

## Typo
> Here, `check_function()` looks for the call of `round()` in both student and solution code, and then `check_result()` runs both (in their respective environments).

* Here, `check_function()` looks for the call of `sum()` in both student and solution code, and then `check_result()` runs both (in their respective environments).

> Whenever there are is a multitude of ways to call a function

* Whenever there is a multitude of ways to call a function

[Source](https://datacamp.github.io/testwhat/articles/checking-function-calls.html)

## Remind / remember
> Remind that functions like `check_object()` and `check_function()` often depend on both the student and solution environment.

* Remember that functions like `check_object()` and `check_function()` often depend on both the student and solution environment.

[Source](https://datacamp.github.io/testwhat/articles/checking-control-flow.html#caution)

## `check_or` or `check_or`
> `check_or` and `check_or` allow you to add logic to your SCT. Instead of running all tests and failing as soon as one of the tests fail, you can conditionally execute tests, and interpret the results separately.

* `check_correct` and `check_or` allow you to add logic to your SCT. Instead of running all tests and failing as soon as one of the tests fail, you can conditionally execute tests, and interpret the results separately.

[Source](https://datacamp.github.io/testwhat/articles/checking-control-flow.html#caution)

## `res` or `result`
> As an example, suppose you want the student to calculate the mean of a vector `vec` and store it in `res`. A possible solution could be:
```r
# vec is predefined for you
vec <- c(1, 2, 3, 4, 5, 6)

# Calculate result
result <- mean(vec)
```

* As an example, suppose you want the student to calculate the mean of a vector `vec` and store it in `result`. A possible solution could be:
```r
# vec is predefined for you
vec <- c(1, 2, 3, 4, 5, 6)

# Calculate result
result <- mean(vec)
```

[Source](https://datacamp.github.io/testwhat/articles/combining-sets-of-SCTs.html#example-1-check_correct)

## Remove “something”
> If something `result` is not correct, you want to dig a little deeper and see if the student used the `mean()` function correctly.

*  If `result` is not correct, you want to dig a little deeper and see if the student used the `mean()` function correctly.

[Source](https://datacamp.github.io/testwhat/articles/combining-sets-of-SCTs.html#example-1-check_correct)

## `test_object()` or `check_object()`

> Because there is clearly something wrong - result is not correct - the ‘check’ sub-SCT, `ex() %>% test_object("result")` is executed again, but loudly this time.

* Because there is clearly something wrong - result is not correct - the ‘check’ sub-SCT, `ex() %>% check_object("result")` is executed again, but loudly this time.

[Source](https://datacamp.github.io/testwhat/articles/combining-sets-of-SCTs.html#example-1-check_correct)

## `test_object` or `check_object`?

> For `testwhat` and DataCamp’s R Backend it communicates with, this can cause problems: there’s a solution enviroment and a student environment (so that `testwhat` can easily compare objects that student created with the object that they should’ve created, for example with `test_object()`)

* For `testwhat` and DataCamp’s R Backend it communicates with, this can cause problems: there’s a solution environment and a student environment (so that `testwhat` can easily compare objects that student created with the object that they should’ve created, for example with `check_object()`)

[Source](https://datacamp.github.io/testwhat/articles/electives.html#blocking-solution-execution)

Cc @filipsch

**Comment by filipsch** [comment]
@Hadrien-lcrx Thanks for this, very helpful!
