### ISSUE TITLE
Don't mention 'Submit Answer' in check_predefined_objects() message.

### ISSUE THREAD

**Issue by richierocks** [datacamp/testwhat#213]
The buttons have been renamed. Change 'Submit Answer' to 'Run Code'.

![screenshot 2018-10-19 16 21 24](https://user-images.githubusercontent.com/197589/47241848-25200280-d3bb-11e8-97bd-c8adca47ff53.png)

**Comment by hermansje** [comment]
Thanks for reporting! Fixed in e2791db.
