### ISSUE TITLE
SCT designed to handle exercises with random component?

### ISSUE THREAD

**Issue by ncarchedi** [datacamp/testwhat#24]
I'm working on a course now where part many of the exercises require the use of `rnorm()` to generate random numbers from a normal distribution. Going forward, I expect many of our courses to incorporate randomness (new intro stats, resampling, simulation, probability, etc.) A simple temporary solution is to add `set.seed()` to the top of every sample/solution script, but this isn't ideal since it's only required for our platform and not central to what we're trying to teach. We can also just use things like `test_function()`, but this is often less desirable than testing the output or value of a student's code.

A really cool and elegant solution could be to have an "SCT" called, for example, `set_seed()` that you add to the SCT portion of an exercise and all it does on the backend is set the same seed in both student and solution environments. For example:

```
set_seed()
test_object(some_random_vector) # this test would normally fail
test_error()
success_msg("Nice!")
```

The seed itself could be set randomly, so that the results appear random to the student if the exercise is refreshed/repeated. For example:

```
> x <- runif(1)
> set.seed(x)
> rnorm(5)
[1]  1.2630 -0.3262  1.3298  1.2724  0.4146
> set.seed(x)
> rnorm(5)
[1]  1.2630 -0.3262  1.3298  1.2724  0.4146
```

@vincentvankrunkelsven Thoughts?

**Comment by filipsch** [comment]
@ncarchedi interesting.
The difficulty with this system is that the RBackend already carries out the student code and the solution code, even before thinking about executing the SCT. So the `set_seed()` function in the SCT would come too late: the results have already been calculated with random numbers that are possibly different for student and solution. 
You could ask the system to redo the execution of student and solution code if there's a set_seed() in the SCT, but that would add a lot of (unnecessary) computation that is rather redundant.
You are right, however, to ask for a function that can deal with randomness in a clean way. I'll look into it more closely.

**Comment by ncarchedi** [comment]
@filipsch Thanks, this would be **very** helpful with the functions course as well.

**Comment by filipsch** [comment]
@ncarchedi we found a way.
Basically, we update RBackend, so that it always sets a random seed right before you submit your script. That way, you can rest assured that student and solution environment will always correspond.
The good part is that you don't have to specify anything extra in the SCTs.

It's pretty funky, but I've got something working in RBackend; I'll make sure to document it thoroughly on Teach as soon as it's available (I guess beginning next week).

**Comment by filipsch** [comment]
https://github.com/datacamp/r-backend/issues/5

**Comment by ncarchedi** [comment]
@filipsch Cool, thanks!!! (cc @tommyjee)

**Comment by tommyjee** [comment]
@filipsch great news!!

**Comment by filipsch** [comment]
@tommyjee The RBackend is an R package that handles requests that the learning interface sends to our servers (contains commands like `init`, `submit` and `console`, corresponding to different actions that users make.
`testwhat` is the R package that contains all these SCT functions, and based on what the student did in his session can tell what mistakes were made.
RBackend: https://github.com/datacamp/RBackend
testwhat: https://github.com/datacamp/testwhat

**Comment by tommyjee** [comment]
@filipsch Ah, I see. I'll definitely check it out. Thanks!

**Comment by filipsch** [comment]
It's live.
