### ISSUE TITLE
`index` arg for test function needs documentation fix.

### ISSUE THREAD

**Issue by JosiahParry** [datacamp/testwhat#44]
the `index` arg doesn't work for each call of the function, rather each call of the function with the same arguments.

ex.  
```
plot(x, y, col = "red")
plot(x, y, col = "blue")
plot(x, y)

test_function("plot", c("x", "y", "col"), index = 1)
test_function("plot", c("x", "y", "col"), index = 2)
test_function("plot", c("x", "y"), index = 3)
```
This throws an error for the third call of `plot()`, because it doesn't have the exact same arguments. But works for the first two.

**Comment by filipsch** [comment]
@JosiahParry This should work I think. Normally `test_function()` selects all `plot()` calls, regardless of the arguments.
Can you point me to the source code of the exercise that is causing the issue so I can experiment?

**Comment by JosiahParry** [comment]
@filipsch, this issue was caused by two functions with almost identical names `chart.RollingPerformace()` and `charts.RollingPerformance()`. The error was being thrown because of different function names in in sct vs solution. Apologize for that. Thanks for the quick response!
