### ISSUE TITLE
Robust testing of ...

### ISSUE THREAD

**Issue by filipsch** [datacamp/testwhat#48]
Several R functions take the 'ellipsis' argument, where you can pass in a bunch of arguments without having to necessarily name them. If you don't name them, `match.call()` doesn't know what to do and it becomes hard to test the arguments.

Need a way to do this properly.

**Comment by filipsch** [comment]
@ncarchedi implemented in the new version of testwhat; hope to make this available in about 10 days.

**Comment by ncarchedi** [comment]
@filipsch Is this available now? If not, do you know approximate ETA? (cc @tommyjee)

**Comment by filipsch** [comment]
@ncarchedi no, because i'm still working on the update of testwhat, where it will be available.
I was delayed by the work on the python stuff last week.
I'll reopen to make it clear it is not yet in production.
Hope to launch new testwhat, and this fix, beginning of next week.
cc @tommyjee

**Comment by filipsch** [comment]
@ncarchedi @tommyjee this is done, you can read up on more information [here](https://github.com/datacamp/testwhat/wiki/test_function#example-4--argument)

**Comment by filipsch** [comment]
@ncarchedi if you feel like the current functionality is not sufficient (I admit it's rather basic, but didn't have a lot of use-cases to start from), just make a new issue and I'll be as responsive as possible.
