### ISSUE TITLE
Make testwhat more robust to user overrides

### ISSUE THREAD

**Issue by filipsch** [datacamp/testwhat#54]
[This exercise](https://campus.datacamp.com/courses/cleaning-data-in-r/1828?ex=7)

If the user submits this (incorrectly):

```
# Print state abbreviations
states

# Make states all uppercase and save result to states_upper
states_upper <- toupper(states)

# Make states_upper all lowercase again
tolower <- tolower(states_upper)
```

he/she overwrites and breaks everything -> make evaluation in solution environment more careful!!
Ideally, student code is executed in a 'student environment' and solution code is executed in a 'solution environment'. (only if old DataCampSCT is phased out...)

**Comment by machow** [comment]
@filisch can check in code, but as I recall isn't this implemented in testwhat?

**Comment by filipsch** [comment]
Nope, that's why it's still an open bug. I attempted to fix this by also executing student code in an child environment of the global environment, but that messed up autocompletion (see issue on r-backend)

**Comment by machow** [comment]
ah, okay, that's good to know--[issue link](https://github.com/datacamp/r-backend/issues/1) for reference.

**Comment by machow** [comment]
This is essentially a limitation of r-backend, without an easy fix. Closing this one, but leaving r-backend issue open.
