### ISSUE TITLE
testing `plot()` calls

### ISSUE THREAD

**Issue by tommyjee** [datacamp/testwhat#56]
Right now, `test_function()` does not catch the difference between `plot(a ~ b)` and `plot(b ~ a)`, or `plot(a, b)` and `plot(b, a)`. Though the arguments `x` and `y` to the `plot()` function are not `...` arguments according to its documentation, `test_function("plot", args = c("x", "y")` results in an error as well.

**Comment by filipsch** [comment]
Could you be a bit more specific, with an example solution code, an example SCT and example submissions and the corresponding feedback they should give?

**Comment by filipsch** [comment]
@tommyjee I'm working on the issue right now.
I don't like it that you're using `test_student_typed()` there, by the way; you can perfectly use 

```
test_function("plot", args = c("lwd", "ylim"))
```

As the wiki article on `test_student_typed()` suggests, you should never use `test_student_typed()` unless it's really necessary. [See here](https://github.com/datacamp/testwhat/wiki/test_student_typed#caution)

I also suggest you read through the [`test_function()` wiki article](https://github.com/datacamp/testwhat/wiki/test_function) to learn more about argument matching.

cc @ncarchedi

**Comment by filipsch** [comment]
@tommyjee Now I see.
Your SCT is incorrect; you have to use 

```
test_function("plot", args = c("x")
```

If you want to test the first argument of the plot call. In your example, you simply put `test_function("plot")`, which will only check whether `plot()` was called, and nothing more. 

You have to explicitly mention which arguments you want to check.

I wrote a test, and everything seems to be fine.

- pre-exercise-code: `x <- seq(0, 2*pi, 0.01); y <- sin(x)`
- solution: `plot(y ~ x, main = 'test', lwd = 4)`
- sct: `test_function('plot', args = c('x', 'main', 'lwd'))`

- submission that passes: `plot(y ~ x, main = 'test', lwd = 4)`
- submission that fails: `plot(x ~ y, main = 'test', lwd = 4)`


Anyways, you're right that there should be resilience to differnt ways of calling the `plot()` function (also with the `data = ` argument), but that's a separate issue. I'll close this issue and open up another one for that.

cc @ncarchedi

**Comment by ncarchedi** [comment]
@tommyjee Please review any SCTs you've written recently where this might be an issue. I'd just do a find-all on `test_function("plot"`

**Comment by tommyjee** [comment]
@filipsch Ah, thank you. That was really helpful.

@ncarchedi I remember I changed the `test_function("plot", ...)` SCT to a series of `test_student_typed()`. I'll make changes so that it uses `test_function()` correctly now.
