### ISSUE TITLE
Testing arguments in function call can result in misleading feedback

### ISSUE THREAD

**Issue by jlooney6** [datacamp/testwhat#57]
Providing arguments in a call to `test_function()` can lead to misleading feedback messages when the submission code and/or the solution code reassigns a variable that was previously passed in as an argument to the function being tested with `test_function()`.

For example, let's take the following desired solution:

```
# Define v as a vector containing 1, 2, and 3
v <- c(1, 2, 3)

# Find missing values: missing
missing <- is.na(v)

# Set variable b to 5
b <- 5
```

We could test the student submissions for this exercise with the following SCT:

```
test_function("is.na", args = "x")
test_object("b")
test_error()
success_msg("Good work!")
```

Let's assume the student made one error by mistyping a variable name.  The student would then run the following submission:

```
# Define v as a vector containing 1, 2, and 3
v <- c(1, 2, 3)

# Find missing values: missing
missing <- is.na(v)

# Set variable b to 5
v <- 5
```

Ideally, the SCT would fail with something like "Did you define `b` without errors?"  Instead, the feedback message is "Did you correctly specify the argument `x` in your call of `is.na()`? The object you specified has length 1, while it should have length 3."

Furthermore, the automatic error highlighting draws the user's attention to the argument `v` inside the call to `is.na()`, even though the error is in the next line.

This issue may also be dangerous for instructors because it causes problems if the solution code reassigns an argument.  For example, if the intended solution was to assign `v` to `5` on the last line:

```
# Define v as a vector containing 1, 2, and 3
v <- c(1, 2, 3)

# Find missing values: missing
missing <- is.na(v)

# Set variable v to 5
v <- 5
```

...and we used the same SCT as above, student submissions defining `v` incorrectly in the last line would show the error in the second line.  For example:

```
# Define v as a vector containing 1, 2, and 3
v <- c(1, 2, 3)

# Find missing values: missing
missing <- is.na(v)

# Set variable v to 5
v <- 6
```

The feedback message in this case would be "Did you correctly specify the argument `x` in your call of `is.na()`?" even though the error is on the last line.

**Comment by filipsch** [comment]
@jlooney6 This is something that is practically impossible to fix given the way `testwhat` is currently implemented. `testwhat` runs the solution in a separate environment, and the solution in a separate environment. When `testwhat` starts, the package only has access to the **ending environment**, and it has no clue whether some variables had different values during execution.

One way to fix this, is by using `eval = FALSE` inside `test_function()`; that way, the variable name `v`, so `"v"` is compared to the variable name in the solution code, not the value that is stored inside the variable `v`.

I know this causes issues, but it's give and take: on the one hand, it's cool that `test_function()` can look at the 'underlying values' of variables; on the other hand, this means that your environment should make sense and nothing funky happend with variables along the way.

We have already been thinking about ways to improve this and keep 'intermediate states' of values at several lines in the code, but then things become very computationally intensive and it would be a nightmare to allow for different orders of performing operations etc.

I'll leave the issue open for now so I know it's an ongoing concern, but I'm not planning on implementing specific fixes for this in the short term. I hope the `eval = FALSE` fix solves things for now.

**Comment by machow** [comment]
closing, since this process is explained on the first page of the wiki. Feel free to open a new issue if the documentation could be made clearer.
