### ISSUE TITLE
test_expression_result() appends default message to custom message

### ISSUE THREAD

**Issue by ncarchedi** [datacamp/testwhat#58]
Unlike most other SCTs, `test_expression_result()` appends a default message (e.g. `Instead, got: ...`) to the custom `incorrect_msg`, which is often undesirable. Here's an example:

![screenshot 2016-08-13 15 07 04](https://cloud.githubusercontent.com/assets/4229089/17834349/5d59e23a-670a-11e6-9d37-b84846fa6606.png)

Comes from [this exercise](https://campus.datacamp.com/courses/statistical-modeling-in-r-part-1/covariates-and-effect-size?ex=2) (course is live for beta testing, so don't push anything to master).

Here's the SCT, used to check whether a student's answer is within 1 of of the (exact) correct answer:

```
test_expression_result("abs(66699 - abs(naive_worth)) <= 1", incorrect_msg = "Did you calculate the difference between the `model_output` to compare the output when there is a fireplace vs. when there isn't?")
```

**Comment by filipsch** [comment]
@ncarchedi what do you suggest? Make this extra info optional? Or simply remove it?

**Comment by ncarchedi** [comment]
@filipsch I suggest removing it when we provide a custom message. Since the student doesn't see the expression we're trying to evaluate in the SCT, they don't have any context for what it should evaluate to.

**Comment by filipsch** [comment]
@ncarchedi OK, I'll do that.

**Comment by filipsch** [comment]
This is fixed; it will no longer happen if you manually specify a message.
