### ISSUE TITLE
Session Disconnected - Plotly Course 

### ISSUE THREAD

**Issue by martijnsublime** [datacamp/testwhat#65]
Course: https://www.datacamp.com/courses/1753. 

Issue: if you execute the solution code right away it runs. However if you are doing the ex. interactively session gets disconnected. See video: https://www.dropbox.com/s/k7p2x5de0zff5rh/plotly_example.mov?dl=0

(not sure it has something to do with testwhat, wasn't sure where to commit the issue)

**Comment by filipsch** [comment]
@martijnsublime I'm looking into it.
Just as a sidenote: it's bad style to use backticks inside comments. Also, use the correct spacing in the R code (there's double spacing in the plotly call)
https://www.dropbox.com/s/heo5i9msgeuyjfp/Screenshot%202016-09-12%2009.22.30.png?dl=0
For more information on the styleguide, see https://www.datacamp.com/teach/documentation#tab_style_guide_r

**Comment by filipsch** [comment]
Fix should be deployed in 7 minutes.
