### ISSUE TITLE
test_ggplot doesn't allow to test order of geom_... functions

### ISSUE THREAD

**Issue by vincentvankrunkelsven** [datacamp/testwhat#68]
**DISCLAIMER:** treat with very low priority, no bug

Someone who's creating a course had a problem with the following exercise: **https://campus.datacamp.com/courses/1974/5359?ex=7** (it's an open course, still in development).
The problem is he wants to test whether `geom_boxplot(...)` is used before `geom_point(...)`. `test_ggplot()` doesn't check the order of the geoms.

I currently proposed the following workaround:

```
# This will check if the ggplot command the student used contains the correct parts
test_ggplot(1)

# This will test that geom_boxplot is used before geom_point (with any signs in between, using a regex)
test_student_typed("geom_boxplot.*geom_point", 
                   fixed=F, 
                   not_typed_msg = "Be sure to switch the order of `geom_point()` and `geom_boxplot()`.")

success_msg("Good work!")
```

I wouldn't fix this specifically for ggplot, I guess this person can get by with the workaround for now. But in general it would be nice to have a way to test the order of certain functions. Maybe with some notation as follows:

```
seq <- test_sequence()
seq %>% test_function("geom_boxplot") %>% test_arg(...)
seq %>% test_function("geom_point") %>% test_arg(...)
```

Feel free to `wontfix` this problem, it's just a suggestion.

**Comment by filipsch** [comment]
won't fix.

**Comment by machow** [comment]
You could probably use a simple regex, like

```
# After all other SCTs
ex() %>% check_code("geom_boxplot.*geom_point")
```
