### ISSUE TITLE
Incorrect highlighting of the error 

### ISSUE THREAD

**Issue by sumedh10** [datacamp/testwhat#73]
When there are two instances of the same `geom_*` layer in different set of instructions, it is expected that by passing the **index** argument to `test_function()` (or `check_function()`), we can correctly test the relevant code. 

However, this doesn’t seem to work properly when testing a set of arguments that exist in both the `geom_*` layers. In the following SCT, when **fill** is mapped incorrectly in the second `geom_tile()` layer, the feedback shows that there is something wrong in the **fill** argument of the first `geom_tile()` layer (even though everything with the first `geom_tile()` layer is correct). 

On the other hand, if **alpha** is incorrect (which exists only in the second `geom_tile()` layer), the feedback correctly points to the second `geom_tile()` layer. 

**P.S.**: I am not sure if the incorrect highlighting of the error is an issue with testwhat or the campus app. 

*** = pre_exercise_code
```
library(ggmap)
library(ggplot2)
download.file("http://s3.amazonaws.com/assets.datacamp.com/production/course_1816/datasets/01-corvallis-map-bw.rds", "01-corvallis-map-bw.rds")
corvallis_map_bw <- readr::read_rds("01-corvallis-map-bw.rds")
 
preds_url <-url("http://s3.amazonaws.com/assets.datacamp.com/production/course_1816/datasets/01_corv_predicted_grid.rds")
preds <- readr::read_rds(preds_url)
close(preds_url)
rm(preds_url)
```

*** = solution
```
# Add a geom_point() layer
ggplot(preds, aes(lon, lat)) +
  geom_point()
 
# Add a tile layer with fill mapped to predicted_price
ggplot(preds, aes(lon, lat)) +
  geom_tile(aes(fill = predicted_price))
 
# Use ggmap() instead of ggplot()
ggmap(corvallis_map_bw) +
  geom_tile(aes(lon, lat, fill = predicted_price),
            data = preds, alpha = 0.8)
```

*** = solution (Test case)
```
# Add a geom_point() layer
ggplot(preds, aes(lon, lat)) +
  geom_point()
 
# Add a tile layer with fill mapped to predicted_price
ggplot(preds, aes(lon, lat)) +
  geom_tile(aes(fill = predicted_price))
 
# Use ggmap() instead of ggplot()
ggmap(corvallis_map_bw) +
  geom_tile(aes(lon, lat, fill = “predicted_price”),
            data = preds, alpha = 0.8)
```

<img width="1678" alt="screenshot 2016-11-07 17 03 09" src="https://cloud.githubusercontent.com/assets/8866417/20149441/46f6e8a8-a67f-11e6-893b-7a36e05310ac.png">

*** = sct
```
test_ggplot(1, exact_aes = TRUE, exact_geom = TRUE)
test_ggplot(2, exact_aes = TRUE, exact_geom = TRUE)
test_function("ggmap", args = "ggmap", incorrect_msg = "Did you call the `ggmap()` function with `corvallis_map_bw` map?")
 
fun <- ex() %>% check_function("geom_tile", index = 2)
fun %>% check_arg("mapping") %>% check_equal()
fun %>% check_arg("data") %>% check_equal()
fun %>% check_arg("alpha") %>% check_equal()
 
test_error()
success_msg("Great work!")
```

The expected result is to highlight the `geom_tile()` call in the third instruction. 

cc @ncarchedi

**Comment by filipsch** [comment]
@sumedh10 
This is a detail of the `testwhat` implementation.
The thing is that `check_function("geom_tile", index = 2)` takes into account __all__ calls of `geom_tile()` in the student's code, not only the second call. This is to be robust against students playing around and using `geom_tile()` too often.

This is what happens:

- `check_function("geom_tile")` looks for all calls of `geom_tile()` in the student's code. It finds two: on line 7 and on line 11.
- Next, `check_arg("mapping")` goes on and checks whether the `mapping` argument is specified. It sees that both calls of `geom_tile()` do that, so both calls are still 'candidates to fulfill the checks'.
- Next, `check_equal()` checks if the actual value of `mapping` corresponds to the solution. More specifically, it looks for a `mapping` argument that equals `aes(lon, lat, fill = predicted_price)`. It checks the `mapping` argument of the first `geom_tile()` call and sees it's no good. Then it checks the `mapping` argument of the second `geom_tile()` call and sees it's no good either. At this point the SCT fails, and simply the first function that failed is highlighted as the incorrect one.

You can solve this by 'ruling out' the first `geom_tile()` call as a candidate, by explicitly checking the `mapping` argument of the first `geom_tile()` call as well. That way, the first `geom_tile()` call will not be considered as a candidate anymore by the time you're checking the second `geom_tile()` call:


```R
test_ggplot(1, exact_aes = TRUE, exact_geom = TRUE)
test_ggplot(2, exact_aes = TRUE, exact_geom = TRUE)
test_function("ggmap", args = "ggmap", incorrect_msg = "Did you call the `ggmap()` function with `corvallis_map_bw` map?")
 
fun1 <- ex() %>% 
   check_function("geom_tile", index = 1) %>% 
   check_arg("mapping") %>% 
   check_equal()

fun2 <- ex() %>% check_function("geom_tile", index = 2)
fun1 %>% check_arg("mapping") %>% check_equal()
fun1 %>% check_arg("data") %>% check_equal()
fun1 %>% check_arg("alpha") %>% check_equal()
 
test_error()
success_msg("Great work!")
```

Can you check if this works?

This was a funky example of something called 'blacklisting' in `testwhat`. You're considering all calls of a particular function as 'candidates', and then each `test_function()` (or `check_function()`, behind the scenes `test_function()` uses `check_function()`) 'crosses of' these candidates whenever a check is satisfies, and they can no longer function as candidates for future checks.

Does this make sense? If so, I'll cast this explanation in an extra section on the `testwhat` wiki!

Great to see you're using the new syntax of `testwhat`, by the way!

cc @machow

**Comment by sumedh10** [comment]
@filipsch 

The SCT you provided works perfectly! Thank you for the thorough explanation.  Actually, it was @ncarchedi who used the new syntax of `testwhat`.

**Comment by filipsch** [comment]
It's explained on the wiki now!
https://github.com/datacamp/testwhat/wiki/test_function#example-3-multiple-function-calls-2
