### ISSUE TITLE
More interesting praise in the success msgs

### ISSUE THREAD

**Issue by richierocks** [datacamp/testwhat#78]
I struggle to come up with interesting ways of saying "Well done!" in calls to `success_msg`. It would be nice to have this automated by using [`praise::praise`](https://www.rdocumentation.org/packages/praise/topics/praise).

**Comment by filipsch** [comment]
Hey, good idea. If you check out `R/reporter.R`, you'll see we now sample from three sentences:

```R
private = list(
    success_msg = sample(c("Good Job!", "Well done!", "Great work!"), 1),
    feedback = NULL
  )
```

Introducing praise might be a nice enhancement.

**Comment by filipsch** [comment]
@richierocks this is live now; You can set `praise = TRUE` inside `success_msg()`, which will cause a praise message to prepend your success message.

**Comment by richierocks** [comment]
```r
praise::praise("${exclamation}! ${adjective} work!")
```

**Comment by filipsch** [comment]
@richierocks ah shoot, i just manually did `praise::praise()` in the `success_msg()`; you want the ability to specify templates and everything?
