### ISSUE TITLE
Check input argument is a string in test_* fns

### ISSUE THREAD

**Issue by richierocks** [datacamp/testwhat#79]
My most common mistake when writing SCTs is forgetting to wrap the code to be tested in quotes.  In these cases, the failure message from the `test_*` function is often a little obscure.

It would be helpful to have a check at the start of each `test_*` function (or possibly the underlying `check_*` functions( that the first argument is a string (or character vector, for those functions that are vectorized.  You can easily check this by using `assert_is_character` or `assert_is_a_string` from `assertive.types`.

**Comment by machow** [comment]
been on prod for a while..
