### ISSUE TITLE
setup_state function for running doc/wiki examples

### ISSUE THREAD

**Issue by machow** [datacamp/testwhat#82]
From pairing w/ @richierocks, would be useful to have a basic function that lets people run SCTs directly, rather than having to put them inside a string. At the bottom of this issue is code we have been passing around. Note that...

1. It doesn't require RBackend, but as such, won't work for test_output_contains or test_error.
2. We need a way to roll in getting messages after failed SCTs.

### Adding RBackend

We could add it in simply, but I think requiring people to install it is a problem, since it is in a private repo. For now, I think we should just leave it out. The relevant parts of RBackend actually might not be much code.

### Failure Messages

Overriding the `DC_reporter$register_feedback` method to something like below should change it to just return the relevant message.

```
feedback <- public$get_feedback()
payload <- testwhat:::generate_payload(feedback, correct = FALSE, ex_type = 'NormalExercise')
payload$message
```

### current setup_state code

```
setup_state <- function(STU_CODE, SOL_CODE, PEC = character()) {
  sol_env <- new.env()
  stu_env <- new.env()
  
  evaluate::evaluate(PEC,      envir=sol_env)
  evaluate::evaluate(SOL_CODE, envir=sol_env)
  evaluate::evaluate(PEC,      envir=stu_env)
  evaluate::evaluate(STU_CODE, envir=stu_env)
  
  tw$clear()
  state <- testwhat:::RootState$new(
    pec = PEC,
    student_code = STU_CODE,
    student_pd = testwhat:::build_pd(STU_CODE),
    student_env = stu_env,
    solution_code = SOL_CODE,
    solution_pd = testwhat:::build_pd(SOL_CODE),
    solution_env = sol_env,
    output_list = list(),
    test_env = new.env(parent=globalenv())
  )
  # testwhat will access the reporter and state from the tw object
  rep <- testwhat:::DC_reporter$new()
  tw$set(state = state, reporter = rep, stack = TRUE)
}
```

**Comment by filipsch** [comment]
This is there now!
