### ISSUE TITLE
test_data_frame(eq_condition = "identical") should distinguish tbl, data.table

### ISSUE THREAD

**Issue by richierocks** [datacamp/testwhat#84]
By default, `test_data_frame()` does not care whether a student uses `data.frame`, `data.table::data.table`, `tibble::data_frame`, or any other data frame variant.  This is absolutely the right behavior when `eq_condition = "equivalent"`.  

However, I would expect a stricter check using `eq_condition = "identical"` to fail, since the objects aren't identical. It seems that that condition only checks that each column is identical; there are no checks on the whole object.

Here's an example.

Solution code:

```{r}
dwarves <- tibble::data_frame(
  name = c('Bashful', 'Doc', 'Dopey', 'Grumpy', 'Happy', 'Sleepy', 'Sneezy'),
  hat_color = c('green', 'brown', 'purple', 'brown', 'yellow', 'green', 'yellow'),
  has_beard = c(TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE)
)
```

Student code:

```{r}
dwarves <- data.frame(
  name = c('Bashful', 'Doc', 'Dopey', 'Grumpy', 'Happy', 'Sleepy', 'Sneezy'),
  hat_color = c('green', 'brown', 'purple', 'brown', 'yellow', 'green', 'yellow'),
  has_beard = c(TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE),
  stringsAsFactors = FALSE
)
```

SCT with `eq_condition = "equivalent"`

```{r}
test_data_frame("dwarves") # correctly passes
```

SCT with `eq_condition = "identical"`

```{r}
test_data_frame("dwarves", eq_condition = "identical") # passes but probably shouldn't
```

I should clarify that this isn't a high priority problem, but I'm trying to understand how `test_data_frame()` works and this is unexpected behavior that isn't clearly documented.

**Comment by machow** [comment]
You can test whether the objects are identical using...

```
ex() %>% check_object('dwarves') %>% check_equal(eq_condition='identical')
```

I'm not sure we should change it, since test_data_frame belongs to the "old syntax", and the check_* syntax allows the expected behavior. (CC @filipsch) thoughts?

**Comment by filipsch** [comment]
@machow agreed!

**Comment by richierocks** [comment]
OK, fair enough.
