### ISSUE TITLE
test_expression_result w/ random component fails

### ISSUE THREAD

**Issue by machow** [datacamp/testwhat#92]
Example below. Not sure what needs to be done here (maybe I missed something?). Note: `cov.rob` has a random component.

*** =pre_exercise_code
```{r}
custom_seed(42)   # doesn't work w/ or w/o it
```

*** =solution
```{r}
library(MASS)
M <- matrix(rnorm(300), nrow=100)
```

*** =sct
```{r}
test_expression_result("cov.rob(M)$cov")
```

**Comment by filipsch** [comment]
@machow the custom seed things only hold for code that is executed inside the student and solution environment, not for expressions that are run inside the test environment during the running of the SCT.

**Comment by machow** [comment]
I think the quickest solution for now is to set the seed in test_expression_result, like

```
test_expression_result("{set.seed(42); cov.rob(M)$cov}")
```

In the long term, we could add pre_code argument to `test_expression_result`

**Comment by filipsch** [comment]
@machow yep good idea.

**Comment by machow** [comment]
solution outlined in linked issue
