### ISSUE TITLE
Always set seed in test_expression_result

### ISSUE THREAD

**Issue by filipsch** [datacamp/testwhat#96]
Referring to issue in stat modeling course: https://github.com/datacamp/courses-statistical-modeling-intro-1/issues/16#issuecomment-294918372

- Always set the seed in `test_expression_result()`, before parsing and running the actual expression. Implementation-wise, this will boil down to adding it in the relevant underlying `check_*()` functions.
- Suggestion: use the seed that's being set by RBackend: `dc$get("script_seed")`, so it's not always the exact same.

**Comment by machow** [comment]
Sounds good, this is very similar to #92 , so I'm closing that one and leaving this open.

**Comment by machow** [comment]
added here https://github.com/datacamp/testwhat/pull/109

(on prod)
