### ISSUE TITLE
R2BayesX error only when evaluating in solution environment

### ISSUE THREAD

**Issue by machow** [datacamp/testwhat#98]
@filipsch (cc @ramnathv )

As discussed w/ @richierocks and Tom in office hours, the following PEC and code works when evaluated as a student submission, but not when initially evaluating the solution in the solution environment. 

The issue seems to be with the `bayesx` function which can't find a variable defined in the solution environment. It goes away when we manually assign that variable to the globalenv(). This sounds like an issue with `bayesx` assuming something will be in the globalenv(). 

*** =pre_exercise_code
```{r}
library(sp)
library(raster)
library(R2BayesX)
library(spdep)

data_dir <- "/usr/local/share/datasets"
london <- readRDS(file.path(data_dir, "london_2017_2.rds"))
```

*** =solution
```{r}
# do this
borough_nb <- poly2nb(london)
borough_gra <- nb2gra(borough_nb)

# MC-NOTE, uncommenting line below solves issue
# assign('borough_gra', borough_gra, envir=globalenv())

# then this
flu_spatial <- bayesx(Flu_OBS ~ HealthDeprivation + sx(i, bs = "spatial", map = borough_gra),
                      offset = log(london$TOTAL_POP),
                      family = "poisson",
                      data = data.frame(london))

```

**Solutions**

Currently, testwhat creates a new env to evaluate the solution (call it `sol_env`), with globalenv() as parent. It seems like what we should be doing is temporarily making `sol_env` the parent of globalenv() instead. This way, we won't change the globalenv, and anything that inappropriately tries to get variables off of that environment will correctly get those variables from its parent, `sol_env`.

Since the student environment is currently globalenv, this would require changing it to be similar to `sol_env`.

**References**

I made an experimental package to make behavior similar to python importing in R, which may be a useful reference, [here](https://github.com/machow/importr). As I recall, the author of magrittr had a similar package (can't find atm), which may be useful to look through.

**Comment by filipsch** [comment]
This is an idea worth investigating, but can make things pretty complicated. I'm not sure if we can assume that every `testwhat` user knows the inner workings of environments and how variables are created an retrieved in them.

As a quick fix, they can use `'___BLOCK_SOLUTION_EXEC___'`, which simply does not run the solution code; you can then use `override_solution()` to manually set variables if you still want to use testwhat functions that require the solution environment (such as `check_object() %>% check_equal()`).

**Comment by machow** [comment]
Okay, after pairing w/ @filipsch I see the light of how testwhat has arranged the student and solution environments. It's clearly a bug / or bad practice in `bayesx`.  For example, the line below evaluates an expression inside `.GlobalEnv`, when it should be using `parent.frame()`:

https://github.com/cran/R2BayesX/blob/master/R/bayesx.construct.mrf.smooth.spec.R#L11

In desperation, we quickly tried to hack the chain of package environments, so that the `R2BayesX` package had a parent with a different value of `.GlobalEnv`, pointing to the current environment. 

```
env_bayes <- as.environment("package:R2BayesX")
env_parent <- parent.env(env_bayes)
env_patch <- new.env(parent = env_parent)
parent.env(env_bayes) <- env_patch
assign(".GlobalEnv", environment(), envir = env_patch)
```

**Comment by filipsch** [comment]
Bottom line: `'___BLOCK_SOLUTION_EXEC___'` is probably what you want to use so you can continue course development.
