### ISSUE TITLE
allow check_equal to run custom expression result of selected code

### ISSUE THREAD

**Issue by machow** [datacamp/testwhat#99]
cc @richierocks @filipsch @ramnathv 

If a solution looks like this...

```
# make sure the y_lim argument is less than 300
some_plot(data, y_lim = c(0, 200))
```

It does not currently seem possible to easily test the argument `y_lim`, since

1. test_student_typed is not well suited for making sure something is less than 300
2. running the expr corresponding to the `y_lim` arg is straightforward, but not customizing the equality check between the results

One solution would be to allow `check_equal` to accept a function that takes whatever is returned by the expression. This function would then return what should ultimately be compared across student and solution. (The same could be done in pythonwhat by making gentle modification to the `name` argument of `check_equal_value`).

**workarounds**

For now, there are a few workarounds

1. use variable assignment. In this case, the solution and sample code could be modified like `y_lim <- c(0, 200); some_plot(data, y_lim = y_lim)`. Then you could test `y_lim` using something like `check_expr("y_lim[1] < 300")`
2. use test_student_typed (or check_code). For testing that a value is less than 300, you could do something like `check_code("([12][0-9][0-9])|300")`.
3. change the exercise to ask for a specific y_lim value, rather than one out of a range.

**Comment by ramnathv** [comment]
I would lean towards (1) as a workaround, since it appears to be the cleanest. It would also work better as we move towards an interface where some code segments are locked. As an aside, once we complete a discussion on workarounds, it would be useful to add them to the wiki, since it is much easier to follow along, instead of diving into the issues.

**Comment by richierocks** [comment]
@machow @ramnath I've rewritten the problem exercise using method (1), as recommended. I don't particularly like it since it makes the exercise a little clunkier, however it will do for now.  Longer term, having `check_less_than()` and `check_greater_than()` would be nice.

**Comment by machow** [comment]
solution is documented here:

https://datacamp.github.io/courses-testwhat-tutorial/advanced-topics.html#test-piece-of-code-flexibly

**Comment by machow** [comment]
I've outlined in detail how check_equal could be expanded here: #101
